---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library("tidyverse")
library("caTools")
library("rpart")
library("rpart.plot")
library("lattice")
library("caret")
```



## Data Importing and cleaning
```{r}
data<-read.csv("corona_tested_individuals_ver_0058.csv")
```


```{r}
data1<-data %>% 
  select(cough,fever,sore_throat,shortness_of_breath,
         head_ache,age_60_and_above,gender.1,result) %>% 
  mutate(gender=gender.1) %>% 
  select(-gender.1)

data1 %>%
  filter(result!="other") %>% 
  filter(age_60_and_above!="NULL")->
  data2

positive_data<-subset(data2,result=="positive")
negative_data<-subset(data2,result=="negative")


sub_neg<-sample_n(negative_data, 50000)
sub_pos<-sample_n(positive_data,50000)


set.seed(42)
data3<-rbind(sub_neg,sub_pos)
rows <- sample(nrow(data3))
data3 <- data3[rows, ]



```


## Data Splitting

```{r}
set.seed(123)
sample = sample.split(data3,SplitRatio = 0.75)

train =subset(data3,sample ==TRUE) 
test =subset(data3, sample==FALSE)
```


## Decision Tree
```{r}
fit <- rpart(result~cough+fever+sore_throat+shortness_of_breath
             +head_ache+age_60_and_above+gender,
             data = train, method = 'class')
rpart.plot(fit)
```

```{r}
predict_unseen <-predict(fit,test,type = 'class')
table_mat <- table(test$result, predict_unseen)
table_mat

fourfoldplot(table_mat, color = c("#CC6666", "#99CC99"),
             conf.level = 0, margin = 1,std='ind.max', main = "Confusion Matrix")+ 
    text(-0.4,0.4, "TN", cex=1) + 
    text(0.4, -0.4, "TP", cex=1) + 
    text(0.4,0.4, "FP", cex=1) + 
    text(-0.4, -0.4, "FN", cex=1)
```

```{r}
accuracy_Test <- sum(diag(table_mat)) / sum(table_mat)
print(paste('Accuracy for test', round(accuracy_Test*100,2)))
```


## Logistic Regression
```{r}
library(boot)
glm.fits=glm(as.factor(result)~cough+fever+sore_throat+shortness_of_breath
             +head_ache+age_60_and_above+gender , data=data3, family = binomial)
summary(glm.fits)
#cv.err=cv.glm(cancer,glm.fits,K=10)$delta[1]
#cv.err

glm.probs=predict(glm.fits,type="response")
glm.pred=rep("0",50000)
glm.pred[glm.probs >0.5]="1"
table_matrix<-table(glm.pred,data3$result)

fourfoldplot(table_matrix, color = c("#CC6666", "#99CC99"),
             conf.level = 0, margin = 1,std='ind.max', main = "Confusion Matrix")+ 
    text(-0.4,0.4, "TN", cex=1) + 
    text(0.4, -0.4, "TP", cex=1) + 
    text(0.4,0.4, "FP", cex=1) + 
    text(-0.4, -0.4, "FN", cex=1)
```
```{r}
accuracy_Test <- sum(diag(table_matrix)) / sum(table_matrix)
print(paste('Accuracy for test', round(accuracy_Test*100,2)))
```


```{r}
mean(glm.pred==data2$result)

step(glm.fits)
```

## LDA
```{r}

trControl <- trainControl(method  = "cv",
                          number  = 5)

ldafit <-train(as.factor(result)~cough+fever+sore_throat+shortness_of_breath
             +head_ache+age_60_and_above+gender,
             method     = "lda",
             trControl  = trControl,
             data=train)
ldafit

pred.class = predict(ldafit, test)
table_matrix<-table(pred.class, test$result)

fourfoldplot(table_matrix, color = c("#CC6666", "#99CC99"),
             conf.level = 0, margin = 1,std='ind.max',
             main = "Confusion Matrix")+ 
    text(-0.4,0.4, "TN", cex=1) + 
    text(0.4, -0.4, "TP", cex=1) + 
    text(0.4,0.4, "FP", cex=1) + 
    text(-0.4, -0.4, "FN", cex=1)
```


```{r}
accuracy_Test <- sum(diag(table_matrix)) / sum(table_matrix)
print(paste('Accuracy for test', round(accuracy_Test*100,2)))
```


```{r}
confusionMatrix(as.factor(pred.class), as.factor(test$result) )
```


## QDA
```{r}
set.seed(23)
qdafit <-train(as.factor(result)~cough+fever+sore_throat+shortness_of_breath
             +head_ache+age_60_and_above+gender,
             method     = "qda",
             trControl  = trControl,
             data=train)
qdafit

pred.class1 = predict(qdafit, test)
table_matrix3<- table(pred.class1, test$result)
fourfoldplot(table_matrix3, color = c("#CC6666", "#99CC99"),
             conf.level = 0, margin = 1,
             std='ind.max',
             main = "Confusion Matrix")+ 
    text(-0.4,0.4, "TN", cex=1) + 
    text(0.4, -0.4, "TP", cex=1) + 
    text(0.4,0.4, "FP", cex=1) + 
    text(-0.4, -0.4, "FN", cex=1)
```
```{r}
accuracy_Test <- sum(diag(table_matrix)) / sum(table_matrix)
print(paste('Accuracy for test', round(accuracy_Test*100,2)))
```


```{r}
mean(pred.class1 == test$result)
confusionMatrix(as.factor(pred.class1), as.factor(test$result ))

```







